language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t 9970850350/docker-react -f Dockerfile.dev .
scripts:
  - docker run -e CI=true 9970850350/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-102055562735"
  bucket_path: "docker-react"
  skip_cleanup: true
  edge: true
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY