language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 9970850350/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true 9970850350/docker-react npm run test